import axios from 'axios';
import type { MitigationRule } from '../types';

interface Props {
  rules: MitigationRule[] | null;
  onWithdraw: () => void;
}

export function MitigationRules({ rules, onWithdraw }: Props) {
  const withdraw = async (id: string) => {
    await axios.delete(`/api/mitigate/${id}`);
    onWithdraw();
  };

  return (
    <div style={{ background: '#1e1e2e', borderRadius: 8, padding: 20, marginBottom: 24 }}>
      <h2 style={{ color: '#fff', marginBottom: 16, fontSize: 16 }}>🛡️ Active Mitigation Rules</h2>
      {!rules?.length ? (
        <div style={{ color: '#555', textAlign: 'center', padding: 20 }}>No active rules</div>
      ) : (
        <table style={{ width: '100%', borderCollapse: 'collapse', color: '#ccc', fontSize: 14 }}>
          <thead>
            <tr style={{ borderBottom: '1px solid #333' }}>
              {['Victim IP', 'Protocol', 'Port', 'Action', 'Auto', 'Expires', ''].map(h => (
                <th key={h} style={{ textAlign: 'left', padding: '8px 12px', color: '#888' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rules.map(r => (
              <tr key={r.id} style={{ borderBottom: '1px solid #2a2a3e' }}>
                <td style={{ padding: '10px 12px', color: '#fff', fontWeight: 600 }}>{r.victimIp}</td>
                <td style={{ padding: '10px 12px' }}>{r.protocol}</td>
                <td style={{ padding: '10px 12px' }}>{r.port ?? 'any'}</td>
                <td style={{ padding: '10px 12px' }}>
                  <span style={{ color: '#ef4444' }}>{r.action}</span>
                </td>
                <td style={{ padding: '10px 12px' }}>{r.autoGenerated ? '✅' : '🔧'}</td>
                <td style={{ padding: '10px 12px', fontSize: 12 }}>
                  {new Date(r.expiresAt).toLocaleTimeString()}
                </td>
                <td style={{ padding: '10px 12px' }}>
                  <button
                    onClick={() => void withdraw(r.id)}
                    style={{
                      background: '#ef444422', color: '#ef4444',
                      border: '1px solid #ef4444', borderRadius: 4,
                      padding: '4px 10px', cursor: 'pointer', fontSize: 12
                    }}
                  >
                    Withdraw
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}