import {
  Controller,
  Get,
  Post,
  Delete,
  Param,
  Body,
  Query,
} from '@nestjs/common';
import { MitigationService } from '../mitigation/mitigation.service';

@Controller('api/mitigate')
export class MitigationController {
  constructor(private readonly mitigationService: MitigationService) {}

  @Get()
  getRules(@Query('status') status?: string) {
    return this.mitigationService.getRules(status);
  }

  @Get('bgp-log')
  getBgpLog() {
    return this.mitigationService.getBgpLog();
  }

  @Get(':id')
  getRuleById(@Param('id') id: string) {
    return this.mitigationService.getRuleById(id);
  }

  @Post()
  createRule(
    @Body()
    body: {
      victimIp: string;
      srcIp?: string;
      protocol?: string;
      port?: number;
      action?: string;
      durationMinutes?: number;
    },
  ) {
    return this.mitigationService.createRule({ ...body, autoGenerated: false });
  }

  @Delete(':id')
  withdrawRule(@Param('id') id: string) {
    return this.mitigationService.withdrawRule(id);
  }
}
