import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { OnEvent } from '@nestjs/event-emitter';
import { v4 as uuidv4 } from 'uuid';
import { MitigationRule } from '../db/entities/mitigation-rule.entity';
import { AttackEvent } from '../db/entities/attack-event.entity';

@Injectable()
export class MitigationService {
  private readonly logger = new Logger(MitigationService.name);

  constructor(
    @InjectRepository(MitigationRule)
    private ruleRepo: Repository<MitigationRule>,
    @InjectRepository(AttackEvent)
    private attackRepo: Repository<AttackEvent>,
  ) {}

  // ─── Auto mitigation — triggered by detection engine ─────────────────────

  @OnEvent('attack.detected')
  async onAttackDetected(attack: AttackEvent) {
    // Check if there's already an active rule for this IP
    const existing = await this.ruleRepo.findOne({
      where: { victimIp: attack.victimIp, status: 'active' },
    });

    if (existing) return;

    const rule = await this.createRule({
      attackId: attack.id,
      victimIp: attack.victimIp,
      srcIp: 'any',
      protocol: this.getProtocolFromAttackType(attack.attackType),
      port: this.getPortFromAttackType(attack.attackType),
      action: 'drop',
      durationMinutes: 10,
      autoGenerated: true,
    });

    // Update attack status to mitigated
    attack.status = 'mitigated';
    await this.attackRepo.save(attack);

    this.logger.log(`Auto-mitigation triggered for attack ${attack.id}`);

    return rule;
  }

  @OnEvent('attack.resolved')
  async onAttackResolved(attack: AttackEvent) {
    const rule = await this.ruleRepo.findOne({
      where: { victimIp: attack.victimIp, status: 'active' },
    });

    if (!rule) return;

    await this.withdrawRule(rule.id);
    this.logger.log(
      `Auto-withdrawal triggered for resolved attack ${attack.id}`,
    );
  }

  // ─── Create a rule ────────────────────────────────────────────────────────

  async createRule(params: {
    attackId?: string;
    victimIp: string;
    srcIp?: string;
    protocol?: string;
    port?: number;
    action?: string;
    durationMinutes?: number;
    autoGenerated?: boolean;
  }): Promise<MitigationRule> {
    const durationMinutes = params.durationMinutes ?? 10;
    const expiresAt = new Date(Date.now() + durationMinutes * 60 * 1000);

    const rule = new MitigationRule();
    rule.id = uuidv4();
    rule.attackId = params.attackId ?? null;
    rule.victimIp = params.victimIp;
    rule.srcIp = params.srcIp ?? 'any';
    rule.protocol = params.protocol ?? 'any';
    rule.port = params.port ?? null;
    rule.action = params.action ?? 'drop';
    rule.status = 'active';
    rule.expiresAt = expiresAt;
    rule.autoGenerated = params.autoGenerated ?? false;

    await this.ruleRepo.save(rule);

    // Push to mock BGP
    this.mockBgpPush(rule);

    return rule;
  }

  // ─── Withdraw a rule ──────────────────────────────────────────────────────

  async withdrawRule(id: string): Promise<MitigationRule | null> {
    const rule = await this.ruleRepo.findOne({ where: { id } });
    if (!rule) return null;

    rule.status = 'withdrawn';
    await this.ruleRepo.save(rule);

    // Notify mock BGP
    this.mockBgpWithdraw(rule);

    return rule;
  }

  // ─── Auto expiry loop — runs every minute ─────────────────────────────────

  async expireRules() {
    const expired = await this.ruleRepo
      .createQueryBuilder('r')
      .where('r.status = :status', { status: 'active' })
      .andWhere('r.expiresAt < NOW()')
      .getMany();

    for (const rule of expired) {
      rule.status = 'withdrawn';
      await this.ruleRepo.save(rule);
      this.mockBgpWithdraw(rule);
      this.logger.log(`Rule ${rule.id} expired and withdrawn`);
    }
  }

  // ─── Query methods for API ────────────────────────────────────────────────

  async getRules(status?: string) {
    const query = this.ruleRepo.createQueryBuilder('r');

    if (status && status !== 'all') {
      query.where('r.status = :status', { status });
    }

    return query.orderBy('r.createdAt', 'DESC').getMany();
  }

  async getRuleById(id: string) {
    return this.ruleRepo.findOne({ where: { id } });
  }

  getBgpLog() {
    return this.bgpLog.slice(-100); // last 100 entries
  }

  // ─── Mock BGP ─────────────────────────────────────────────────────────────
  // Simulates pushing rules to a real router via BGP Flowspec

  private bgpLog: Array<{
    timestamp: Date;
    action: string;
    rule: string;
    router: string;
  }> = [];

  private mockBgpPush(rule: MitigationRule) {
    const entry = {
      timestamp: new Date(),
      action: 'PUSH',
      rule: `${rule.action} ${rule.protocol} → ${rule.victimIp}${rule.port ? `:${rule.port}` : ''} from ${rule.srcIp}`,
      router: 'mock-router-01',
    };

    this.bgpLog.push(entry);
    this.logger.warn(`[Mock BGP] PUSH rule to ${entry.router}: ${entry.rule}`);
  }

  private mockBgpWithdraw(rule: MitigationRule) {
    const entry = {
      timestamp: new Date(),
      action: 'WITHDRAW',
      rule: `${rule.action} ${rule.protocol} → ${rule.victimIp}${rule.port ? `:${rule.port}` : ''} from ${rule.srcIp}`,
      router: 'mock-router-01',
    };

    this.bgpLog.push(entry);
    this.logger.warn(
      `[Mock BGP] WITHDRAW rule from ${entry.router}: ${entry.rule}`,
    );
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────

  private getProtocolFromAttackType(attackType: string): string {
    switch (attackType) {
      case 'syn-flood':
        return 'tcp';
      case 'udp-amplification':
        return 'udp';
      case 'icmp-flood':
        return 'icmp';
      default:
        return 'any';
    }
  }

  private getPortFromAttackType(attackType: string): number | undefined {
    switch (attackType) {
      case 'udp-amplification':
        return 53; // DNS port
      default:
        return undefined;
    }
  }

  async hasActiveRule(victimIp: string): Promise<boolean> {
    const rule = await this.ruleRepo.findOne({
      where: { victimIp, status: 'active' },
    });
    return !!rule;
  }

  async withdrawAllActiveRules() {
    const activeRules = await this.ruleRepo.find({
      where: { status: 'active' },
    });

    for (const rule of activeRules) {
      await this.withdrawRule(rule.id);
    }
  }
}
