import { Entity, PrimaryColumn, Column, CreateDateColumn } from 'typeorm';

@Entity('mitigation_rules')
export class MitigationRule {
  @PrimaryColumn()
  id: string;

  @Column({ type: 'varchar', nullable: true })
  attackId: string | null;

  @Column()
  victimIp: string;

  @Column({ default: 'any' })
  srcIp: string;

  @Column({ default: 'any' })
  protocol: string;

  @Column({ type: 'int', nullable: true })
  port: number | null;

  @Column({ default: 'drop' })
  action: string; // 'drop' | 'rate-limit' | 'redirect-scrubbing'

  @Column({ default: 'active' })
  status: string; // 'active' | 'withdrawn'

  @CreateDateColumn()
  createdAt: Date;

  @Column()
  expiresAt: Date;

  @Column({ default: true })
  autoGenerated: boolean;
}
