import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
} from 'typeorm';

@Entity('mitigation_rules')
export class MitigationRule {
  @PrimaryColumn()
  id: string;

  @Column({ nullable: true })
  attackId: string;

  @Column()
  victimIp: string;

  @Column({ default: 'any' })
  srcIp: string;

  @Column({ default: 'any' })
  protocol: string;

  @Column({ nullable: true })
  port: number;

  @Column({ default: 'drop' })
  action: string; // 'drop' | 'rate-limit' | 'redirect-scrubbing'

  @Column({ default: 'active' })
  status: string; // 'active' | 'withdrawn'

  @CreateDateColumn()
  createdAt: Date;

  @Column()
  expiresAt: Date;

  @Column({ default: true })
  autoGenerated: boolean;
}
