export interface FlowStat {
  dstIp: string;
  pps: number;
  bps: number;
}

export interface AttackEvent {
  id: string;
  timestamp: string;
  victimIp: string;
  attackType: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  pps: number;
  bps: number;
  status: string;
}

export interface MitigationRule {
  id: string;
  attackId: string | null;
  victimIp: string;
  srcIp: string;
  protocol: string;
  port: number | null;
  action: string;
  status: string;
  createdAt: string;
  expiresAt: string;
  autoGenerated: boolean;
}

export interface BgpLogEntry {
  timestamp: string;
  action: 'PUSH' | 'WITHDRAW';
  rule: string;
  router: string;
}

export interface Stats {
  activeAttacks: number;
  totalAttacksToday: number;
  mitigatedToday: number;
}